platform:ios,'7.0'

link_with 'ABCFrameWork', 'ABCFrameWorkTests'

pod 'AFNetworking'
pod 'SDWebImage'
pod 'JSONModel'
pod 'Masonry'
pod 'Reachability'
pod 'YTKKeyValueStore'
pod 'SVProgressHUD'
pod 'RJImageLoader'
pod 'Aspects'
